name: 'GitHub Actions Crpto Rates Bot'

on:
  workflow_dispatch

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Rate'
        run: bash ./get_rate.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Singapore' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: "sgusgroup10@gmail.com"
          password: "Sgus@group10##"
          subject: Daily Crypto Rate Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: sgusgroup10@gmail.com
          from: GitHub Actions
          content_type: text/html
